baseURL = "https://allthathappens.com/"
languageCode = "en-us"
title = "All That Happens"
theme = "mundana"
summaryLength = 25
copyright = "Dale St. Marthe - All rights reserved"
enableEmoji = true
#disqusShortname = "your-shortname-here"
#googleAnalytics = "UA-1XXXXXXX1-1"
alertbar = false

[permalinks]
  posts = '/:year/:month/:title/'

[frontmatter]
  lastmod = ['lastmod', ':fileModTime', ':default']

[taxonomies]
	author = "authors"
	tag = "tags"
	category = "categories"

[params]
  logo = "/images/logo.png"
  description ="Answering Your Everyday Why"
  #mailchimp = "you can provide a mailchimp-link here"


[params.social]
  github = "<username>"
  linkedin = "<username>"
  xing = "<username>"
  medium = "<username>"
  twitter = "<username>"
  instagram = "<username>"

## Main Menu
[[menu.main]]
    name = "The All"
    weight = 100
    identifier = "All"
    url = "/article"
[[menu.main]]
    name = "Trending"
    identifier = "Trending"
    weight = 200
    url = "/article/trending/"
[[menu.main]]
    name = "Imprint"
    identifier = "imprint"
    weight = 200
    url = "/static/imprint"
