baseURL = "https://allthathappens.com/"
languageCode = "en-us"
title = "All That Happens"
theme = "mundana"
summaryLength = 25
copyright = "Dale St. Marthe - All rights reserved"
enableEmoji = true
#disqusShortname = "your-shortname-here"
#googleAnalytics = "UA-1XXXXXXX1-1"
alertbar = true

[permalinks]
  posts = ':title/'

[frontmatter]
  lastmod = ['lastmod', ':fileModTime', ':default']

[taxonomies]
	author = "authors"
	tag = "tags"
	category = "categories"

[params]
  logo = "/images/logo.png"
  navLogo = "/images/athlogowords.svg"
  description ="Answering Your Everyday Why"
  mailchimp = "https://chimpstatic.com/mcjs-connected/js/users/d36e79b42a287b4496fe407e2/36813f5d459934bd9d7845380.js"
mailprotect= "b_d36e79b42a287b4496fe407e2_ec8bb659a9"

[params.social]
  github = "<username>"
  linkedin = "<username>"
  xing = "<username>"
  medium = "<username>"
  twitter = "<username>"
  instagram = "<username>"

## Main Menu
[[menu.main]]
    name = "The All"
    weight = 100
    identifier = "All"
    url = "/article"
[[menu.main]]
    name = "Trending"
    identifier = "Trending"
    weight = 200
    url = "/article/trending/"
[[menu.main]]
    name = "Imprint"
    identifier = "imprint"
    weight = 200
    url = "/static/imprint"
