baseURL = "https://www.allthathappens.com"
languageCode = "en-us"
title = "All That Happens News"
theme = "mundana"
summaryLength = 25
copyright = "Dale St. Marthe - All rights reserved"
enableEmoji = true
#disqusShortname = "your-shortname-here"
#googleAnalytics = "G-XXXXXXX"
enableGitInfo = true


[outputs]
    home = ["HTML", "RSS", "JSON"]

[permalinks]
  posts = ':title/'

[frontmatter]
  lastmod = ['lastmod', ':fileModTime', ':default']

[taxonomies]
	author = "authors"
	tag = "tags"
	category = "categories"

[params]
  logo = "/images/logo.png"
  alertbar = true
  navLogo = "/images/athlogowords.svg"
  mailchimp = "https://gmail.us12.list-manage.com/subscribe/post?u=d36e79b42a287b4496fe407e2&amp;id=ec8bb659a9&amp;f_id=003343e0f0"
  mailprotect = "b_d36e79b42a287b4496fe407e2_ec8bb659a9"
  gRecaptchaSitekey = "6LeoXRolAAAAAAcQHmcBYg0uRb_z4NEzG6G0UuZV"
  gRecaptchaSecret = "6LeoXRolAAAAACWQl5LziCRP-vnjVi9TnchCWY8i"
  googleTag - "G-T57XGJWMW5 "

[meta]
  description ="Our vision is to provide informative and engaging content that answers some of the most searched questions and ideas on the web. From gaming to tech, science, and trends. Even the mundane things in life, we cover it all. Join us on this journey of discovery and knowledge-sharing."
  keywords = ["blog", "ai", "software", "space", "news", "global news", "online","geek"]

[params.social]
  github = "<username>"
  linkedin = "<username>"
  xing = "<username>"
  medium = "<username>"
  twitter = "<username>"
  instagram = "<username>"

## Main Menu
[[menu.main]]
    name = "The All"
    weight = 100
    identifier = "he All"
    url = "/theall"
[[menu.main]]
    name = "Trending"
    identifier = "Trending"
    weight = 200
    url = "/trending/"
