baseURL = 'http://themundane.com/'
languageCode = 'en-us'
title = 'The Mundane'


# Theme Settings
theme = "mediumish-gohugo-theme"
[params]
  Author = "lgaida"
[author]
  name = "lgaida"
  homepage = "http://lgaida.de"
