backend:
  name: git-gateway
  branch: main

publish_mode: editorial_workflow
media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads
site_url: https://allthathappens.com
sortable_fields: ["section", "title", "author"]
collections:
  - name: post
    label: Post
    folder: content
    path: "{{section}}/{{title}}/{{slug}}"
    slug: "index"
    format: yaml-frontmatter
    create: true
    fields:
      - { name: title, label: Title, widget: string }
      - { name: author, label: Author, widget: string }
      - { name: summary, label: Summary, widget: text }
      - {
          name: section,
          label: Section,
          widget: select,
          options: ["happening", "tech", "science", "gaming", "theall"],
        }
        - {
          name: categories,
          label: Categories,
          widget: select,
          options: ["Happening", "Tech", "Science", "Gaming", "The All"],
        }
      - {
          label: "Featured Image",
          name: "thumbnail",
          widget: "image",
          default: "./"
          required: false,
          media_library:
            config:
              multiple: true
        }
      - { name: body, label: Body, widget: markdown }
      - { name: tags, label: Tags, widget: list,  default: [""], max: 18 }
      - { name: keywords, label: Keywords, widget: list, default: [""], max: 18 }
      - { label: "Publish Date", name: "date", widget: "datetime" }
  