backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

publish_mode: editorial_workflow
media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads
site_url: https://allthathappens.com

collections:
  - name: post
    preview_path: "{{section}}/{{slug}}"
    label: Post
    folder: content
    create: true
    fields:
      - { name: title, label: Title, widget: string }
      - { name: author, label: Author, widget: string }
      - { name: summary, label: Summary, widget: text }
      - {
          name: section,
          label: Section,
          widget: select,
          options: ["Happening", "Tech", "Science", "Gaming", "The All"],
        }
      - {
          label: "Featured Image",
          name: "thumbnail",
          widget: "image",
          required: false,
        }
      - { name: body, label: Body, widget: markdown }
      - { label: "Publish Date", name: "date", widget: "datetime" }
