---
backend:
  name: git-gateway
  branch: main
publish_mode: editorial_workflow
media_folder: static/images/uploads
public_folder: /images/uploads
site_url: https://allthathappens.com
collections:
  - name: post
    label: Post
    folder: content
    path: "{{place}}/{{title}}/{{slug}}"
    slug: index
    format: yaml-frontmatter
    sortable_fields:
      - categories
      - title
      - author
    create: true
    fields:
      - name: title
        label: Title
        widget: string
      - name: author
        label: Author
        widget: string
      - name: body
        label: Body
        widget: markdown
      - name: summary
        label: Summary
        widget: text
        required: false
      - name: place
        label: Section
        widget: select
        options:
          - happening
          - tech
          - science
          - gaming
          - theall
      - label: Categories
        name: categories
        widget: select
        multiple: true
        options:
          - label: Happening
            value: Happening
          - label: Tech
            value: Tech
          - label: Science
            value: Science
          - label: Gaming
            value: Gaming
          - label: The All
            value: The All
      - label: Featured Image
        name: thumbnail
        widget: image
        default: ./
        required: false
      - name: tags
        label: Tags
        widget: list
        add_to_top: true
        max: 18
        required: false
      - name: keywords
        label: Keywords
        widget: list
        add_to_top: true
        max: 18
        required: false
      - label: Publish Date
        name: date
        widget: datetime
        date_format: "YYYY-MM-DD"
        time_format: "HH:mm:ss Z"
      - label: Draft
        name: draft
        default: false
        widget: hidden
      - label: Layout
        name: layout
        default: single
        widget: hidden
