backend:
  name: git-gateway
  branch: main
publish_mode: editorial_workflow
media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads
site_url: https://allthathappens.com

collections:
  - name: post
    label: Post
    folder: content
    path: "{{field.section}}/{{slug}"
    slug: "index"
    format: yaml-frontmatter
    create: true
    fields:
      - { name: title, label: Title, widget: string }
      - { name: author, label: Author, widget: string }
      - { name: summary, label: Summary, widget: text }
      - {
          name: section,
          label: Section,
          widget: select,
          options: ["happening", "tech", "science", "gaming", "theall"],
        }
      - {
          label: "Featured Image",
          name: "thumbnail",
          widget: "image",
          required: false,
        }
      - { name: body, label: Body, widget: markdown }
      - { name: tags, label: Tags, widget: list, max: 18 }
      - { name: keywords, label: Keywords, widget: list, max: 18 }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - {
          label: "Layout",
          name: "layout",
          widget: "hidden",
          default: "article",
        }
