---
name: Hugo build
on:
  push:
    paths:
      - content/**
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.110.0'
        extended: true

    - name: Build Hugo site
      run: hugo
      
    - name: Add & Commit
      uses: EndBug/add-and-commit@v9.1.1
      with:
        message: "Added new blog post"
        add: 'content'
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
