---
name: Hugo build
on:
  push:
    paths:
      - content/**
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Build Hugo
        uses: lowply/build-hugo@v0.110.0


