---
name: Hugo build
on: push
  paths:
     'content/*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2.6.0
        with:
          hugo-version: 0.110.0
          extended: true
      - name: Build Hugo site
        run: hugo
---
